spring.application.name=mcintyre-lab

server.port=8081

# Database Connection
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ckdieogybeoxzawzelgt
spring.datasource.password=JxnvaKDQJeuhTu6B
spring.datasource.driver-class-name=org.postgresql.Driver

# Table Creation Strategy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Hibernate Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JWT Configuration
jwt.secret=0ff92eeb136c05b779d642dc7176c6b0bc54abe7227f12b208bfdd35e2044d1b
jwt.expiration=86400000